server:
  port: 8010
spring:
  application:
    name: order
  datasource:
    name: hyper_eat
    url: jdbc:mysql://localhost:3306/hyper_eat?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hyperEat.entity